// Suppliers
export const FETCH_SUPPLIERS_REQUEST = 'FETCH_SUPPLIERS_REQUEST';
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS';
export const FETCH_SUPPLIERS_FAILURE = 'FETCH_SUPPLIERS_FAILURE';

// Categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

// Subcategories
export const FETCH_SUBCATEGORIES_REQUEST = 'FETCH_SUBCATEGORIES_REQUEST';
export const FETCH_SUBCATEGORIES_SUCCESS = 'FETCH_SUBCATEGORIES_SUCCESS';
export const FETCH_SUBCATEGORIES_FAILURE = 'FETCH_SUBCATEGORIES_FAILURE';

// Raw Materials
export const FETCH_RAW_MATERIALS_REQUEST = 'FETCH_RAW_MATERIALS_REQUEST';
export const FETCH_RAW_MATERIALS_SUCCESS = 'FETCH_RAW_MATERIALS_SUCCESS';
export const FETCH_RAW_MATERIALS_FAILURE = 'FETCH_RAW_MATERIALS_FAILURE';

// Supplier Categories
export const FETCH_SUPPLIER_CATEGORIES_REQUEST = 'FETCH_SUPPLIER_CATEGORIES_REQUEST';
export const FETCH_SUPPLIER_CATEGORIES_SUCCESS = 'FETCH_SUPPLIER_CATEGORIES_SUCCESS';
export const FETCH_SUPPLIER_CATEGORIES_FAILURE = 'FETCH_SUPPLIER_CATEGORIES_FAILURE';
